---
title: "Module17_downsampling_analysis"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}

# clear global enviroment
rm(list = ls())

# initiate timer
start.time <- proc.time()

# List of packages to load
packages2load <- c("Seurat", 
                   "plyr", "dplyr", "tidyr", "reshape2", "RColorBrewer", "ggplot2", "gridExtra", 
                   "DT", "flexdashboard", "ggpmisc", "ggpmisc", "ggExtra", "grid", "ggrepel", "scales", 
                   "future")

# load packages
lapply(packages2load, library, character.only = TRUE)

```


```{r check available input files}

show.available.files <- FALSE
if (show.available.files){
  list.files("Preprocessed Datasets/")
}

```

```{r parameter specification}

# Specify data directories
dir.preprocessed <- "Preprocessed Datasets/"


# specify inputs and outputs
input.file.df <- data.frame(
  downsampling_factor = c(0.05, 0.125, 0.25, 0.5, 1),
  files = c("Module1_p4_neural_5pctDS_040220.Rdata",
            "Module1_p4_neural_12_5pctDS_040220.Rdata",
            "Module1_p4_neural_25pctDS_040220.Rdata",
            "Module1_p4_neural_50pctDS_040220.Rdata",
            "Module1_p4_neural_differentiation_300120.Rdata")
)

cluster.resolution <- 0.3

group_barcode.filter.flag <- T
group_barcode.filter.list <- list(EB8 = c("EB8"),
                                  DIV1 = c("DIV1"),
                                  DIV7 = c("DIV7"))

# print inline
print.inline <- F

```


```{r analysis log}

# Module
df.log <- data.frame()
df.log[nrow(df.log)+1, 1] <- as.character("Module")
df.log[nrow(df.log), 2] <- as.character("")
df.log[nrow(df.log), 3] <- as.character("17, Downsampling Analysis")
colnames(df.log) <- c("Description", "Variable Name", "Value")

# User 
df.log[nrow(df.log)+1, 1] <- as.character("User")
df.log[nrow(df.log), 2] <- as.character("")
df.log[nrow(df.log), 3] <- as.character(Sys.getenv("USERDOMAIN"))

# Date
df.log[nrow(df.log)+1, 1] <- as.character("Date")
df.log[nrow(df.log), 2] <- as.character("")
df.log[nrow(df.log), 3] <- as.character(Sys.time())

# Input files
df.log[nrow(df.log)+1, 1] <- as.character("Input File (.Rdata)")
df.log[nrow(df.log), 2] <- as.character("input.file.df$files")
df.log[nrow(df.log), 3] <- as.character(paste(input.file.df$files, collapse = ", "))

# Downsampling Factors
df.log[nrow(df.log)+1, 1] <- as.character("Downsampling Factors")
df.log[nrow(df.log), 2] <- as.character("input.file.df$downsampling_factor")
df.log[nrow(df.log), 3] <- as.character(paste(input.file.df$downsampling_factor, collapse = ", "))

# Grouping Flag
df.log[nrow(df.log)+1, 1] <- as.character("Barcode Grouping Flag")
df.log[nrow(df.log), 2] <- as.character("group_barcode.filter.flag")
df.log[nrow(df.log), 3] <- as.character(group_barcode.filter.flag)


# Cluster Resolution
df.log[nrow(df.log)+1, 1] <- as.character("Cluster Resolution")
df.log[nrow(df.log), 2] <- as.character("cluster.resolution")
if (length(cluster.resolution) > 1){
  df.log[nrow(df.log), 3] <- paste(cluster.resolution, collapse=", ")
} else {
  df.log[nrow(df.log), 3] <- as.character(cluster.resolution)
}

df.log[nrow(df.log)+1, 1] <- as.character("Figures Printed in Notebook")
df.log[nrow(df.log), 2] <- as.character("print.inline")
df.log[nrow(df.log), 3] <- as.character(print.inline)


```



```{r function to rename CellTypes to Barcode (fix artefact of earlier analysis pipeline)}

fix.barcode.label <- function (so){
  # merge CellType and Barcode, if necessary
  meta.data.names <- names(so@meta.data)
  
  if (("CellType" %in% meta.data.names) & ("Barcode" %in% meta.data.names)){
    if (DefaultAssay(so) == "integrated"){
      barcode <- so@meta.data[["Barcode"]]
      celltype <- so@meta.data[["CellType"]]
      barcode[is.na(barcode)] <- celltype[is.na(barcode)] 
    } else {
      barcode <- so@meta.data[["CellType"]]
    }
  } else if (!("CellType" %in% meta.data.names) & ("Barcode" %in% meta.data.names)) {
    barcode <- so@meta.data[["Barcode"]]
  } else if (("CellType" %in% meta.data.names) & !("Barcode" %in% meta.data.names)) {
    barcode <- so@meta.data[["CellType"]]
    
  } else {stop("Problem with CellType/Barcode metadata detected. Troubleshooting required")}
  
  so@meta.data[["Barcode"]] <- barcode
  
  return(so)
}

```

```{r load data, message=FALSE, warning=FALSE}

# load query dataset
so.list <- list()
default.assays <- c()

for (i in 1:dim(input.file.df)[1]){
  load(paste(dir.preprocessed, as.vector(input.file.df$files[i]), sep = ""))
  so <- fix.barcode.label(so)
  default.assays[as.character(as.vector(input.file.df$downsampling_factor[i]))] <- DefaultAssay(so)
  so.list[[as.character(as.vector(input.file.df$downsampling_factor[i]))]] <- so
  rm(so)
}


```



```{r assess relationships}

df.ds <- NULL
df.ds.strata <- NULL

if (group_barcode.filter.flag){
ncell.mat.strata <- matrix(nrow = length(so.list), ncol = length(group_barcode.filter.list))
}

for (i in 1:length(so.list)){
  cur.so <- so.list[[i]]
  cur.ds <- as.numeric(names(so.list)[i])

  # get clusters for specified reslution
  cur.so <- FindClusters(object = cur.so, resolution = cluster.resolution, verbose = 0, algorithm = 1, modularity.fxn = 1)

  exp.std <- cur.so@reductions[["pca"]]@stdev
  exp.var <- exp.std^2
  exp.var.rel <- exp.var / sum(exp.var)
  exp.var.rel.cumsum <- cumsum(exp.var.rel)
  
  
  df.ds.cur <- data.frame(
    ds.factor <- cur.ds,
    n.cells <- dim(cur.so)[2],
    n.genes <- dim(cur.so)[1],
    n.pc80 <- sum(exp.var.rel.cumsum < 0.8) + 1,
      n.clusters <- length(as.vector(unique(cur.so@meta.data[["seurat_clusters"]])))
  )
  
  colnames(df.ds.cur) <- c("ds", "n.cells", "n.genes", "n.pc80", "n.clusters")
  
  
  
  if (group_barcode.filter.flag){
    for (j in 1:length(group_barcode.filter.list)){
      pattern <- paste(group_barcode.filter.list[[j]], collapse="|")
      ncell.mat.strata[i, j] <- sum(grepl(pattern, cur.so@meta.data[["Barcode"]]))
    }
  }
  
  df.ds <- bind_rows(df.ds, df.ds.cur)
  
  
  so.list[[i]] <- cur.so 
  
  
}


if (group_barcode.filter.flag){ 
  rownames(ncell.mat.strata) <- names(so.list)
  colnames(ncell.mat.strata) <- names(group_barcode.filter.list)
  ncell.df.strata <- as.data.frame(ncell.mat.strata)
}

# group_barcode.filter.list <- list(EB8 = c("EB8"),
#                                   DIV1 = c("DIV1"),
#                                   DIV7 = c("DIV7"))

```


```{r plot umaps, fig.width = 15, fig.height=4}

plt.umap.list <- list()

for (i in 1:length(so.list)){
    cur.so <- so.list[[i]]
  cur.ds <- as.numeric(names(so.list)[i])
  
  n.clusters <- length(as.vector(unique(cur.so@meta.data[["seurat_clusters"]])))
  
  plt.umap.list[[as.character(cur.ds)]] <- DimPlot(cur.so, reduction = "umap", label = T)  + 
    ggtitle(label = paste(signif(100*cur.ds, 3) , "% (", n.clusters ," c)", sep  ="")) +
  xlab("UMAP 1") + ylab("UMAP 2")
}

plt.umap <- CombinePlots(plots = plt.umap.list, length(so.list), legend = 'none')

if (print.inline) print(plt.umap)


```



```{r}


var2plt <- c("n.cells", "n.genes", "n.pc80", "n.clusters")
names(var2plt) <- c("N Cell Detected", "N Genes Detected", "80% Variance Explained by N PC components", "N Clusters Detected")

var2plt.desc <- c("Cells", "Genes", "Variance", "Clusters")

normalize.flag <- F

df.ds.norm <- df.ds
for (i in 1:length(var2plt)){
  df.ds.norm[ ,var2plt[i]] <-  df.ds.norm[ ,var2plt[i]]  / max( df.ds.norm[ ,var2plt[i]] )
}

plt.list <- list()
for (i in 1:length(var2plt)){
  
  df.cur <- df.ds[, c("ds", var2plt[i])]
  colnames(df.cur) <- c("x", "y")
  df.cur <- df.cur[complete.cases(df.cur), ]
  
  
  if (normalize.flag) df.cur$y <- df.cur$y / max(df.cur$y )

  nlmod<-nls(y~a*x/(b+x),
             data = df.cur, 
             start = c( a = max(df.cur$y),
                        b=median(df.cur$x))) 
  
  maxy <- max(df.cur$y)
  meanx <-median(df.cur$x)
  
  ascend.order <-df.cur$y[length(df.cur$y)] >  df.cur$y[1]
  
  # if (ascend.order){
      min.y <-  min(df.cur$y)
      max.y <- max(df.cur$y)
  # }
      
      y.val.range <- abs(max.y - min.y)
      scale.factor <- 0.2 *y.val.range
  
      min.y <- min.y - scale.factor
      max.y <- max.y + scale.factor
      

  
  a.val <- coef(nlmod)[[1]]
  b.val <- coef(nlmod)[[2]]
  
  x.range <- seq(0, 1, by = 0.01)
  if (ascend.order){
  y.range <- seq(min.y, max.y, by = (a.val/500))

  } else {
   y.range <- seq(max.y, min.y, by = -(a.val/500)) 
  
  }
  
  df.model <- data.frame(x = x.range, y = a.val*x.range/(b.val+x.range))
  
  plt.list[[var2plt[i]]] <- df.cur %>%
    ggplot(aes(x = x, y = y)) +
    geom_line(data = df.model, aes(x, y), color = "tomato") + 
    geom_hline(yintercept = a.val, linetype = 2) +
    geom_vline(xintercept = b.val, linetype = 2) +
    geom_point() +
    ggtitle(var2plt.desc[i]) +
    xlab("Downsampling Factor") +
    ylab(names(var2plt)[i]) +
     theme_classic()+
    xlim(0, 1) + 
  ylim(min.y, max.y) 

}

plt.scatters <- CombinePlots(plots = plt.list, length(plt.list), legend = 'none')

if (print.inline) print(plt.scatters)


```


```{r stratify}


if (group_barcode.filter.flag){
  ncell.df.strata.v2 <- ncell.df.strata
  ncell.df.strata.v2 <- as.data.frame(apply(ncell.df.strata.v2, 2, function(x) x/max(x)))
  ncell.df.strata.v2$ds <- as.numeric(rownames(ncell.df.strata))
  ncell.df.strata.long.v2 <- pivot_longer(ncell.df.strata.v2, cols = names(ncell.df.strata))
  
  plt.stata.norm <- ncell.df.strata.long.v2 %>%
    ggplot(aes(x = ds, y = value, color = name)) +
    geom_point() + geom_line()+
    xlab("Downsampling Factor") +
    ylab("N Cells (normalized)") +
    theme_classic()+
    xlim(0, 1) 
  
  ncell.df.strata.v3 <- ncell.df.strata
  ncell.df.strata.v3$ds <- as.numeric(rownames(ncell.df.strata))
  ncell.df.strata.long.v3 <- pivot_longer(ncell.df.strata.v3, cols = names(ncell.df.strata))
  
  plt.stata.raw <- ncell.df.strata.long.v3 %>%
    ggplot(aes(x = ds, y = value, color = name)) +
    geom_point() + geom_line()+
    xlab("Downsampling Factor") +
    ylab("N Cells") +
    theme_classic() +
    xlim(0, 1) 
  
  if (print.inline){
    print(plt.stata.raw)
    print(plt.stata.norm)
  } 
}


```


Downsampling Analysis
===================================== 

Row 
-----------------------------------------------------------------------

### UMAP

```{r plt.umaps, fig.height= 4, fig.width = 15}
print(plt.umap)
```


Row 
-----------------------------------------------------------------------

### Cells

```{r plt cells}
print(plt.list[[1]])
```

### Genes

```{r plt genes}
print(plt.list[[2]])
```

### Variance

```{r plt variance}
print(plt.list[[3]])
```


### Clusters

```{r plt clusters}
print(plt.list[[4]])
```

Barcode Grouping
===================================== 

Row 
-----------------------------------------------------------------------

### Recovered Cells (N)

```{r plt.raw}
if (group_barcode.filter.flag) print(plt.stata.raw) 
```

### Recovered Cells (Normalized)

```{r plt.norm}
if (group_barcode.filter.flag) print(plt.stata.norm) 
```


Log (Module 17)
===================================== 

```{r table.log_current, message=FALSE, warning=FALSE}

# Run time
end.time <- proc.time()
elapsed.time <- round((end.time - start.time)[[3]], 2)
df.log[nrow(df.log)+1, 1] <- as.character("Run Time (s)")
df.log[nrow(df.log), 2] <- as.character("elapsed.time")
df.log[nrow(df.log), 3] <- as.character(elapsed.time)

df.log_Module_17 <- df.log

knitr::kable(df.log_Module_17)

```


