---
title: "UMAP Expression Panel"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}

rm(list = setdiff(ls(), c("data.path", "user")))
invisible({gc()})

# initiate timer
start.time <- proc.time()

packages2load <- c("Seurat", "scater", "scMiko", "plyr", "dplyr", "tidyr", "reshape2", "tidyverse",
                   "DT", "flexdashboard")

# load packages
invisible({lapply(packages2load, library, character.only = TRUE)})

```



```{r parameter specification}



# Query input
input.file <- "R189_M01_NM2_p12_Meso_061020.Rdata"
# input.file <- "R247_M01_NM2_p12_LungTrouble_061020.Rdata"
# input.file <- "R6_M02_BC2_allGBM_271020.Rdata"
# input.file <- "R65_M01_NM2_p11_neural_DIV7_270820.Rdata"
# input.file <- "R71_M01_NM2_p10_CGR8_310820.Rdata"
# input.file <- "R304_M27_NM2_M02_BC2_allGBM_tumorStringent_tier1_251120.Rdata"
# input.file <- "R73_M02_NM2_M02_neuroDif_p41011_010920.Rdata"
# input.file <- "M01_NM2_R1_test_300720.Rdata"

# save file
# output.file <- "CGR8_DIV7_integrated_neural_expression_res1_200121.csv"


# Data subsampling
subsample_factor <- 1 # OPTIONAL; range 0 to 1 (default = 1)

# specify cluster resolution
# cluster.resolution <- 1

clean.clusters <- T

# subset data
subset.df <- NA
# subset.df <- data.frame(field = "seurat_clusters", subgroups = c(0:20))
# subset.df <- data.frame(field = "Barcode", subgroups = "PBS")

which.species <-  "Hs"

# which.grouping <- "seurat_clusters"

# which.input <- list(
#   
#   # gene list input format options:
#   #   0: Manual input; vector of genes (e.g., which.gene.set = c("cd70", "cd34"))
#   #   1: M09_type1_queries.csv; gene.sets.type1 
#   #   2: M09_type2_queries.csv; gene.sets.type2; .csv file
#   #   3: cluster DEG
#   #   4: top N cluster markers
#   #   5: M09_type5_queries.csv; GO/Reactome genesets
#   #   6: scMiko internal geneset
#   query_input_format = 1,
#   do.module = NA, #options: T, F, NA; if NA, takes default, otherwise overides. 
#   
#   # specify gene set (only if query_input_format == 1 | 2 | 5 | 6)
#   which.gene.set =c('NeuList_HH210127') # character (e.g., sex.specific)
# )

which.gene.set <- c('MesoList_210129') 


```

```{r get marker panel}

  gene.sets.type1 <- read.csv("M09_type1_queries.csv", header = TRUE, stringsAsFactors = F)
  colnames(gene.sets.type1) <- rmvCSVprefix(colnames(gene.sets.type1))
  
  stopifnot(which.gene.set %in% names(gene.sets.type1))
  markers_of_interest <- gene.sets.type1[[which.gene.set]] # REQUIRED if query_input_format == 1
  # meta.module.flag <- meta.module.helper( which.input$do.module,FALSE)
  
  if (exists("markers_of_interest") && "data.frame" %in% class(markers_of_interest)){
  markers_of_interest <- janitor::clean_names(markers_of_interest, "screaming_snake")
  }
  
  markers_of_interest <- markers_of_interest[markers_of_interest != ""]
  
  
```


```{r load data, warning = FALSE}

# Specify data directories
dir.preprocessed <- "Preprocessed_Datasets/"


if (!exists("data.path") & !exists("user")) {
  stop("data.path and user variables do not exist in global enviroment. Ensure that these are specified in .Rprofile. If specified, try restarting Rstudio.")
}

# load data
warning("Importing data...")
if (!grepl(".Rdata|.RData", input.file)) input.file <- paste0(input.file, ".Rdata")
load(paste(data.path, dir.preprocessed, input.file, sep = ""))


if (!exists("gNames.list")) gNames.list <- prepGeneList(so, objects())

if (!(exists("subset.df"))) subset.df <- "no.subset"

# prep seurat object
prep.list <- prepSeurat2(so, e2s = gNames.list, 
                         species = which.species, resolution= 1, subset = subset.df, 
                         subsample = subsample_factor, M00_subgroup.path = "M00_subgroups.csv",
                         terms2drop = c("ica", "tsne", "nmf", "gsva", "deg"), rmv.pattern = "so", 
                         scale.reprocessed = F, neighbors.reprocessed = F, keep.default.assay.only = T)

# unpack results
if (exists("so")) try({rm(so)}, silent = T)
so.query <- prep.list$so
current.assay <- prep.list$assay
n.cells <- prep.list$n.cell
rm(prep.list)
invisible({gc()})

if (clean.clusters) so.query <- cleanCluster(so.query, return.plots = F)

# assert factor order
u.clust.meta <- unique(as.numeric(as.character(so.query@meta.data[["seurat_clusters"]])))
so.query@meta.data[["seurat_clusters"]] <- factor(so.query@meta.data[["seurat_clusters"]], 
                                                  levels = u.clust.meta[order(u.clust.meta)])
Idents(so.query) <- so.query@meta.data[["seurat_clusters"]]

```
```{r}

library(schex)

if (which.species == "Mm"){
  markers_of_interest <- firstup(markers_of_interest)
} else if (which.species == "Hs"){
   markers_of_interest <- toupper(markers_of_interest) 
}

n.bin <- ncol(so.query)/1000
if (n.bin < 30) n.bin <- 30
if (n.bin >150) n.bin <- 150

gene.query <- markers_of_interest
so.query <- make_hexbin(so.query, n.bin, dimension_reduction = "UMAP")


plt.feature.list <- list()
for (i in 1:length(gene.query)){
  # for (i in 1:6){
    which.features <- gene.query[i]
    p.type <- p.lab <- ""
    # subtitle = paste0(p.lab, ", ", p.type), 

  try({

plt.2 <- plot_hexbin_gene(
  so.query,
  type = "data",
  gene = which.features,
  action = "prop_0",
  title = NULL,
  xlab = NULL,
  ylab = NULL
) +
  theme_miko(legend = F, center.title = T) +
  xlab("UMAP 1") + ylab("UMAP 2") +
  labs(title = which.features, fill = "Expression") +  # subtitle = "Expression Fraction",
  theme(
  
  plot.background = element_blank(),    # Background of the entire plot
  
  panel.background = element_blank(),   # Background of plotting area
  panel.border = element_blank(),       # Border around plotting area.
                                       # fill argument should be NA
  
  panel.grid = element_blank(),         # All grid lines
  panel.grid.major = element_blank(),   # Major grid lines
  panel.grid.minor = element_blank(),   # Minor grid lines
  
  panel.grid.major.x = element_blank(), # Vertical major grid lines
  panel.grid.major.y = element_blank(), # Horizontal major grid lines
  panel.grid.minor.x = element_blank(), # Vertical minor grid lines
  panel.grid.minor.y = element_blank()  # Vertical major grid lines
) + theme(
  axis.title = element_blank(),         # Change both x and y axis titles
  
  axis.title.x = element_blank(),       # Change x axis title only
  axis.title.x.top = element_blank(),   # For x axis label on top axis
  
  axis.title.y = element_blank(),       # Change y axis title only
  axis.title.y.right = element_blank(), # For y axis label on right axis
) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

# plt.feature.list[[which.features]] <- cowplot::plot_grid(plt.1, plt.2)

plt.feature.list[[which.features]] <- plt.2

    
  }, silent = T)
}

```



```{r, fig.width=10, fig.height=10}

n.dim <- ceiling(sqrt(length(plt.feature.list)))

plt.top.hits <- cowplot::plot_grid(plotlist = plt.feature.list, ncol = n.dim, nrow = n.dim)

# plt.top.hits


 # ggsave("umap_expression.png", plot = plt.top.hits, width = 2*n.dim, height = 2*n.dim, device = "png")

```

