---
title: "Reference Mapping"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
editor_options: 
  chunk_output_type: inline
knit: (function(inputFile, encoding) {
    rmarkdown::render(input = inputFile,
      encoding = encoding,
      output_file = if (exists("user")){paste0(
        xfun::sans_ext(inputFile), '_',user, "_", format(Sys.Date(), "%d%m%y"), '.html'
      )} else {paste0(xfun::sans_ext(inputFile), '_',"Guest", "_", format(Sys.Date(), "%d%m%y"), '.html')},
      output_dir = if (exists("data.path")) paste0(data.path, "/HTML_Reports") else NULL
    )
  })
---



```{r setup, include=FALSE}

# clear global enviroment
rm(list = setdiff(ls(), c("data.path", "user")))
invisible({gc()})

# initiate timer
start.time <- proc.time()

# List of packages to load
packages2load <- c("Seurat", "scMiko",
                   "dplyr", "tidyr", "RColorBrewer", "ggplot2", 
                   "flexdashboard", "future", 
                   "parallel", "doParallel", "foreach")

# load packages
invisible(lapply(packages2load, library, character.only = TRUE))

```



```{r analysis specifications}

# parameter specification

parameter.list <- list(
# input.file = "R65_M01_NM2_p11_neural_DIV7_270820.Rdata",
# input.file = "R71_M01_NM2_p10_CGR8_310820.Rdata",
  # input.file = "R73_M02_NM2_M02_neuroDif_p41011_010920.Rdata",
  input.file = "M01_NM2_R1_test_300720.Rdata",
    # is.reference = F,
  # input.file = "R304_M27_NM2_M02_BC2_allGBM_tumorStringent_tier1_251120.Rdata",
    cluster.resolution = 1,
    subsample_factor = 1,
    subset.data = NA,
    species = "Mm"
)


barcode.list = list(
GL261 = "GL261", 
CT2A = "CT2A"
)
# barcode.list = list(
#   WT = "WT",
#   C50 = "C50",
#   C68 = "C68",
#   C15 = "C15",
#   C2 = "C2",
#   C76  = "C76"
# )


# print inline
print.inline <- FALSE # OPTIONAL; TRUE/FALSE

# save PDF
save.pdf <- T
update.log <- T


```




```{r load data, warning = FALSE}

message("Importing data...\n")


# Specify data directories
dir.preprocessed <- "Preprocessed_Datasets/"

if (!exists("data.path") & !exists("user")) {
  stop("data.path and user variables do not exist in global enviroment. Ensure that these are specified in .Rprofile. If specified, try restarting Rstudio.")
}

# load query dataset
warning("Importing data...")
input.file <- parameter.list$input.file
if (!grepl(".Rdata|.RData", input.file)) input.file <- paste0(input.file, ".Rdata")
load(paste(data.path, dir.preprocessed, input.file, sep = ""));

if (!exists("gNames.list")) gNames.list <- prepGeneList(so, objects())

t2d <- c("ica", "tsne", "nmf", "corr", "gsva", "deg", "integration.anchors")

# prep seurat object
prep.list <- prepSeurat2(so, e2s = gNames.list, 
                         species =  parameter.list$species, resolution= parameter.list$cluster.resolution, 
                         subset.data = parameter.list$subset.data, 
                         subsample = parameter.list$subsample_factor, M00_subgroup.path = "M00_subgroups.csv",
                         terms2drop = t2d, rmv.pattern = "so", keep.default.assay.only = T)

# unpack results
if (exists("so")) try({rm(so)}, silent = T)
so.query <- prep.list$so
current.assay <- prep.list$assay
n.cells <- prep.list$n.cell
rm(prep.list);
invisible({gc()})


```


```{r analysis log, include = FALSE}

# Initiate and fill analysis Log
df.log <- initiateLog("33, Diversity")
df.log <- addLogEntry("PDF saved", save.pdf, df.log, "save.pdf")
df.log <- addLogEntry("Update Central Log", update.log, df.log, "update.log")
df.log <- addLogEntry("Print Inline", print.inline, df.log, "print.inline")


```


```{r get past module logs, include = FALSE}
# determine prior log history
cur.env <- objects()
module.logs <- cur.env[grep("^df.log_Module",cur.env)]

```

```{r recode barcodes}


if (exists("barcode.list") && (length(barcode.list) > 0)){

df.meta <- so.query@meta.data

# relabel barcodes
bc.list <-barcode.list

df.meta$bc <- NA
for (i in 1:length(bc.list)){
  
  pattern <- bc.list[[i]]
  pattern.replace <- names(bc.list)[i]
  df.meta$bc[grepl(pattern, df.meta$Barcode)] <- pattern.replace
}

so.query@meta.data <- df.meta
  
} else {
  
  
  u.bc <- unique(so.query@meta.data[["Barcode"]])
  bc.list <- list()
  for (i in 1:length(u.bc)){
    bc.list[[i]] <- u.bc[i]
  }
  names(bc.list) <- u.bc
so.query@meta.data[["bc"]] <- so.query@meta.data[["Barcode"]]
}

```



```{r diversity parameter, fig.width = 13, fig.height = 5}

bc.all <- unique(unlist(bc.list))

df.div <- NULL

  q <- 10^((seq(-2, 2, by = 0.01)))
  q <- q[!(q %in% c(0, 1))]

for (i in 1:length(bc.all)){
  
  bc.name <- bc.all[i]
  so.sub <- so.query[ ,so.query@meta.data[["bc"]] %in% bc.name]
  
  so.sub <- FindNeighbors(so.sub)
  # so.sub <- FindClusters(so.sub, resolution = parameter.list$cluster.resolution)
  so.sub <- FindClusters(so.sub, resolution = 1)
  
  df.tab <- NULL
  df.tab <- data.frame(table(so.sub@meta.data[["seurat_clusters"]]))
  df.tab$p <- df.tab$Freq/sum(df.tab$Freq)
  
  for (j in 1:length(q)){
    df.div <-bind_rows(df.div,
                       data.frame(q = q[j],
                                  D = (sum(df.tab$p^q[j]))^(1/(1-q[j])),
                                  bc = bc.name, 
                                  n.clusters = nrow(df.tab)))
  }

}
  
  df.div$bc <- factor( df.div$bc, levels = bc.all)

  
  plt.diversity.plot <-  df.div %>%
    ggplot(aes( x = log10(q), y = D, color = bc)) +
    geom_path(size = 1) + 
      theme_miko(legend = T) + 
      ggthemes::scale_color_ptol() + 
      xlab("Diversity Parameter q") + 
      ylab("Diversity Index Dq") + 
      geom_vline(xintercept = c(1, 2), linetype = "dashed") + 
      labs(title = "Cluster-based diversity scoring", subtitle = "General diversity index Dq to quantify diversity across orders of diversity q", color = "Barcode", caption = "q<<1: Clonal Richness\nq=1: Shannon index\nq=2: 1/Simpson Index\nq>>2: Number of 'main drivers'")
    
    
   plt.n.species.plot <-  df.div %>%
      dplyr::filter(log10(q) == 2) %>%
      ggplot(aes(x = bc, y = D, fill = bc)) + 
      geom_bar(stat = "identity") + 
      ggthemes::scale_fill_ptol() + 
      theme_miko(legend = T) + 
      ylab("Effective Number of Species") + 
      xlab("Barcode") + 
     geom_text(aes(y = -0.5, label = signif(D, 3))) + 
      labs(title = "Effective Number of Species", subtitle = "Inverse Simpson Index", fill = "Barcode")
   
   cowplot::plot_grid(plt.diversity.plot, plt.n.species.plot)
   

```








