---
title: "Module15_cluster_assessment"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}

# clear global enviroment
rm(list = ls())

# initiate timer
start.time <- proc.time()

# List of packages to load
packages2load <- c("Seurat", 
                   "plyr", "dplyr", "tidyr", "reshape2", "RColorBrewer", "ggplot2", "gridExtra", 
                   "DT", "flexdashboard", "ggpmisc", "ggpmisc", "ggExtra", "grid", "ggrepel", "scales", 
                   "scClustViz")

# load packages
lapply(packages2load, library, character.only = TRUE)

```


```{r check available input files}

show.available.files <- FALSE
if (show.available.files){
  list.files("Preprocessed Datasets/")
  }

```

```{r parameter specification}


# Specify data directories
dir.preprocessed <- "Preprocessed Datasets/"

# Query input
input.file <- "Module1_pilot4_GL261_CT2A_scaleAll_080120.Rdata"
# input.file <- "Module2_integrated_lung_CIT_vs_End_EVLP_131219.Rdata"

subsets <- data.frame
# Data subsampling
subsample_factor <- 1 # OPTIONAL; range 0 to 1 (default = 1)

# specify cluster resolution
cluster.resolution <- c(0.15, 0.5, 1, 5)

# print inline
print.inline <- F

# dimension reduction (UMAP, PCA)
which.reduction <- "umap"

# cluster labels (use to label clusters; can include partial labels - unlabel clusters will remain unlabeled)
cluster.annotations <- data.frame(cluster = NA,
                                  label = NA)



```


```{r function to rename CellTypes to Barcode (fix artefact of earlier analysis pipeline)}

fix.barcode.label <- function (so){
  # merge CellType and Barcode, if necessary
  meta.data.names <- names(so@meta.data)
  
  if (("CellType" %in% meta.data.names) & ("Barcode" %in% meta.data.names)){
    if (DefaultAssay(so) == "integrated"){
      barcode <- so@meta.data[["Barcode"]]
      celltype <- so@meta.data[["CellType"]]
      barcode[is.na(barcode)] <- celltype[is.na(barcode)] 
    } else {
      barcode <- so@meta.data[["CellType"]]
    }
  } else if (!("CellType" %in% meta.data.names) & ("Barcode" %in% meta.data.names)) {
    barcode <- so@meta.data[["Barcode"]]
  } else if (("CellType" %in% meta.data.names) & !("Barcode" %in% meta.data.names)) {
    barcode <- so@meta.data[["CellType"]]
    
  } else {stop("Problem with CellType/Barcode metadata detected. Troubleshooting required")}
  
  so@meta.data[["Barcode"]] <- barcode
  
  return(so)
}

```

```{r load data, message=FALSE, warning=FALSE}

# load query dataset
load(paste(dir.preprocessed, input.file, sep = ""))
so <- fix.barcode.label(so)
so.query <- so
so.input <- so.query
rm(so)

current.assay <- DefaultAssay(so.query)

# subsample (for dev purposes)
n.subset <- round(subsample_factor *ncol(so.input))
cell.ind <- sample(x = seq(1, ncol(so.input)), size = n.subset, replace = FALSE, prob = NULL)
so.query <- SubsetData(so.query , cells = cell.ind)

```



```{r}
# determine prior log history
cur.env <- objects()
module.logs <- cur.env[grep("^df.log_Module",cur.env)]

```

```{r}

for (i in 1:length(cluster.resolution)) {
  so.query <- FindClusters(object = so.query, resolution = cluster.resolution[i], verbose = 0, algorithm = 1, modularity.fxn = 1)
}

current.assay <- DefaultAssay(so.query)
# get cluster results (as data.frame)

try({load(svClust.filename)})

if (!exists("sCVdata_list")){
  
  
  
  pattern <- paste(current.assay, "_snn.", sep = "")
  # cluster.cols <- grepl("res[.0-9]+$", names(getMD(so.query)))
  cluster.cols <- grepl(pattern, names(getMD(so.query)))
  cluster.results <- getMD(so.query)[ ,cluster.cols]
  
  cluster.cols <- !(colnames(cluster.results) %in% paste(current.assay, "_snn_res.0", sep = ""))
  cluster.results <- cluster.results[ ,cluster.cols]
  
  sCVdata_list <- CalcAllSCV(
    inD=so.query,
    clusterDF= cluster.results,
    assayType= DefaultAssay(so.query),     #specify assay slot of data
    assaySlot = "data",
    DRforClust=which.reduction,   #reduced dimensions for silhouette calc
    exponent=exp(1),    #log base of normalized data
    pseudocount=1,
    DRthresh=0.1,        #gene filter - minimum detection rate
    testAll=F,           #stop testing clusterings when no DE between clusters
    FDRthresh=0.05,
    calcSil=T,           #use cluster::silhouette to calc silhouette widths
    calcDEvsRest=T,
    calcDEcombn=T
  )
  
  
  save(so.query,sCVdata_list,
       file=svClust.filename)
  
}

```


```{r}

runShiny(
  filePath=svClust.filename,
  
  outPath="./",
  # Save any further analysis performed in the app to the
  # working directory rather than library directory.
  
  annotationDB="org.Mm.eg.db",
  # This is an optional argument, but will add annotations.
  
  cellMarkers=list("Cortical precursors"=c("Mki67","Sox2","Pax6",
                                           "Pcna","Nes","Cux1","Cux2"),
                   "Interneurons"=c("Gad1","Gad2","Npy","Sst","Lhx6",
                                    "Tubb3","Rbfox3","Dcx"),
                   "Cajal-Retzius neurons"="Reln",
                   "Intermediate progenitors"="Eomes",
                   "Projection neurons"=c("Tbr1","Satb2","Fezf2",
                                          "Bcl11b","Tle4","Nes",
                                          "Cux1","Cux2","Tubb3",
                                          "Rbfox3","Dcx")
  ),
  # This is a list of canonical marker genes per expected cell type.
  # The app uses this list to automatically annotate clusters.
  
  imageFileType="png"
  #Set the file format of any saved figures from the app.
)

```

