---
title: "Module25_ActivitySpectrum"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r load libraries, include=FALSE}

# clear global enviroment                          
rm(list = ls())

# initiate timer
start.time <- proc.time()

# load packages
library(scMiko)
library(WGCNA)
library(topGO)
library(ape)
library(RCy3)
modulePackages(module.number = 9)

```


```{r subset lists}

subset.list <- list(
  no.subset=data.frame(field = NA,
                       subgroups = NA),
  renca.tumor.4000ds.T12=data.frame(field = "seurat_clusters",
                                    subgroups = c(0,2,3,5,6,7,9,15)),                # Renca Tumor
  cadiac.p6=data.frame(field = "seurat_clusters",
                       subgroups = c(0, 3, 4, 5, 9)),                                # cardiac tissue p6
  cardiac.p10=data.frame(field = "seurat_clusters",
                         subgroups = c(0,6,8,10,2,3)),                               # cardiac tissue p10
  p4.gbm.scaled.tumor=data.frame(field = "seurat_clusters",
                                 subgroups = c(0, 15, 4, 36, 10, 19, 29, 33, 32)),   # cardiac tissue p10
  invivo.screen.NSG=data.frame(field = "Condition",
                               subgroups = c("NSG")),   # cardiac tissue p10
  invivo.screen.BALB=data.frame(field = "Condition",
                                subgroups = c("BALB")),   # cardiac tissue p10
  invivo.EMT6.sc = data.frame(field = "seurat_clusters",
                              subgroups = c(1,2,3))
  
)


```


```{r}


cluster.resolution <- 1

which.subset <- "p4.gbm.scaled.tumor"
subset.df <- subset.list[[which.subset]] # NA specified as "no.subset"

# query.file <- "Module2_Renca_cell_nuc_sci_T12_4000ds_Celsius_integrated_240220.Rdata"
# query.file <- "Module1_invivo_EMT6_kumar2018_080420.Rdata"
# query.file <- "Module16_UHN_0238_filtered_aggr_labledv2_300120.Rdata" # best power = 3
query.file <- "Module1_pilot4_GL261_CT2A_scaleAll_080120.Rdata"


which.gene.set = "CancerSEA_Hs" # character

dir.preprocessed <- "Preprocessed Datasets/"

downsample.factor <-1 # 1 if unspecified

which.species <- "Mm"

print.inline <- F

```



```{r analysis log}

df.log <- inititateLog("25, Functional activity spectrum")

# Query File
df.log <- addLogEntry("Query File", query.file, df.log, "query.file")
# Directory
df.log <- addLogEntry("Directory", dir.preprocessed, df.log, "dir.preprocessed")
# Downsample factor
df.log <- addLogEntry("Downsample factor", downsample.factor, df.log, "downsample.factor")
# which.species
df.log <- addLogEntry("Species", which.species, df.log, "which.species")
# Cluster resolution
df.log <- addLogEntry("Cluster Resolution", cluster.resolution, df.log, "cluster.resolution")
# print.inline
df.log <- addLogEntry("Print inline", print.inline, df.log, "print.inline")
# which data subset
df.log <- addLogEntry("Data subset ID", which.subset, df.log, "which.subset")
# data subset
df.log <- addLogEntry("Data subset field", subset.list$field, df.log, "subset.list$field")
# data subset
df.log <- addLogEntry("Data subset members", subset.list$subgroups, df.log, "subset.list$subgroups")



# get prior log history
cur.env <- objects()
module.logs <- cur.env[grep("^df.log_Module",cur.env)]

```

```{r import seurat object}

# import and preprocess data
load(getLoadPath(query.file, dir.preprocessed))
so.query <- prepSeurat(so)
rm(so)

```

```{r get clusters and assay}

# get current assay
current.assay <- DefaultAssay(so.query)

# get cluster
so.query <- setResolution(so.query, cluster.resolution)

```


```{r seurat data subsetting }

# subset seurat object
so.query <- subsetSeurat(so.query, subset.df)

```


```{r prior log history}
# get prior log history
cur.env <- objects()
module.logs <- cur.env[grep("^df.log_Module",cur.env)]

```


```{r prep seurat  gene list}
gNames.list <- prepGeneList(so.query, objects())
```



```{r convert to symbol}

# convert ENSEBLE to GENE names in Seurat object
# gene.rep <-  check.gene_rep(gNames.list, as.vector(rownames(so.query@assays[[current.assay]]@scale.data)))
gene.rep <-  checkGeneRep (gNames.list, as.vector(rownames(so.query@assays[[current.assay]]@scale.data)))

if (gene.rep == "ensembl"){
  # so.query <- ens2sym(so = so.query, gNames.list = gNames.list, convert.RNA = TRUE)
  so.query <- ens2sym.so(so = so.query, gNames.list = gNames.list)
  gene.rep <-  checkGeneRep(gNames.list, as.vector(rownames(so.query@assays[[current.assay]]@scale.data)))
  # gene.rep <-  check.gene_rep(gNames.list, as.vector(rownames(so.query@assays[[current.assay]]@scale.data)))
}


```


```{r get clusters and set assay}

if (DefaultAssay(so.query) == "integrated"){
  # DefaultAssay(so.query) <- "RNA"
  # so.query <-NormalizeData(so.query, verbose = FALSE)
  # so.query <- ScaleData(so.query, verbose = FALSE)
  # so.query <- FindVariableFeatures(so.query, selection.method = "vst", nfeatures = 3000)
  DefaultAssay(so.query) <- "SCT"
} 

current.assay =  DefaultAssay(so.query)

```



```{r downsample Seurat}

if (exists("downsample.factor")){
  so.query <- downsampleSeurat(so.query, downsample.factor)
}

```



```{r umap by cluster}

# get GGplot handle for cluster umap
plt.umap_by_cluster <- cluster.UMAP(so.query, group.by = "seurat_clusters", pt.size = T)
if (print.inline) plt.umap_by_cluster

```


```{r get gene sets}

  scMiko.geneSets <- scMiko::geneSets
  stopifnot(which.gene.set %in% names(scMiko.geneSets))
  markers_of_interest <- as.data.frame(scMiko.geneSets[[which.gene.set]])

```



```{r compute meta module scores }


  if(!exists("moi.df")) moi.df <- (markers_of_interest)

  gNames <- gNames.list
  plt.clustermarkers_by_umap <- list()
  available_markers <- c()

  markers_of_interest <- names(moi.df)
  
  exp.mat.new <- NULL
  
  all.list <- list()
  for (i in 1:length(markers_of_interest)){
    
    # get meta module name
    cur.marker <- markers_of_interest[i]
    
    # clean dataset and include only those available in seurat object
    cur.features <- as.character(moi.df[,i][moi.df[,i] != ""])
    cur.features <- cleanFilterGenes(cur.features, so.query, which.species)

    if (length(cur.features) == 0) next
    
    # append module prefix and get module scores
    # if (prefix.label != ""){
    #   module.name <- paste(prefix.label, "-",cur.marker, sep = "")
    # } else {
      module.name <- cur.marker
    # }
    

    so.query.try = NA
      so.query.try <-  try(AddModuleScore(so.query,  
                                          features = list(cur.features),
                                          ctrl = 50,
                                          name = "new.module",
                                          nbin = 5), silent = T)
      
      if (is.na(so.query.try)) next


    # assign name to modlue score
    names(so.query.try@meta.data)[names(so.query.try@meta.data) %in% paste("new.module", 1, sep = "")] <- module.name
    so.query@meta.data[[module.name]] <- so.query.try@meta.data[[module.name]]
    
    # concat scores to dataframe
    cur.module.df <- as.data.frame(so.query@meta.data[[module.name]])
    colnames(cur.module.df) <- module.name
    exp.mat.new <- bind_cols(exp.mat.new, cur.module.df)

    available_markers[i] <- module.name
    all.list[[module.name]] <- cur.features

  }
  
  # get all scores and cast as matrix
  exp.mat.new.mat.t <- t(as.matrix(exp.mat.new))

  # concat scores to seurat objects
  exp.mat.1 <-so.query@assays[[DefaultAssay(so.query)]]@data
  colnames(exp.mat.new.mat.t) <- colnames(exp.mat.1)
  exp.mat.1 <- rbind(exp.mat.1, exp.mat.new.mat.t)
  so.query@assays[[DefaultAssay(so.query)]]@data <- exp.mat.1
  
  exp.mat.2 <-so.query@assays[[DefaultAssay(so.query)]]@scale.data
  colnames(exp.mat.new.mat.t) <- colnames(exp.mat.2)
  exp.mat.2 <- rbind(exp.mat.2, exp.mat.new.mat.t)
  so.query@assays[[DefaultAssay(so.query)]]@scale.data <- exp.mat.2
  markers_of_interest <- available_markers[!is.na(available_markers)]
  

if (exists("so.query.try")) rm("so.query.try")
  
  rm("exp.mat.1")
  rm("exp.mat.2")
```


```{r}
# get module data

exp.mat <- getExpressionMatrix(so.query)

module.mat <- exp.mat[rownames(exp.mat) %in% markers_of_interest, ]

df.module <-as.data.frame(t(module.mat))

```


```{r, include = F}

heat.object <- getHeat(module.mat)



```


```{r, fig.width=5, fig.height=10}

df.module.long <- pivot_longer(df.module, cols = colnames(df.module))

df.module.long <- df.module.long %>%
  group_by(name) %>%
  mutate(a.rank = as.numeric(rank(value)))


# df.module.long.ref <- df.module.long %>%
#   group_by(name) %>%
#   summarize(which.rank = which.min(abs(value)))


module.order <- rownames(module.mat)[heat.object[["rowInd"]]]
module.order <- module.order[order(module.order)]
df.module.long$name <- factor(df.module.long$name, levels = module.order)

which.rank <- c()
for (i in 1:length(module.order)){
  df.module.long.sub <- df.module.long[df.module.long$name == module.order[i], ]
  which.rank[i] <- df.module.long.sub$a.rank[which.min(abs(df.module.long.sub$value))]
}

df.rank <- data.frame(name = module.order, which.rank = which.rank)

df.module.long <- merge(df.module.long, df.rank, by = "name")

scale.limits <- max(abs(df.module.long$value))

# df.module.long.sub <- df.module.long[df.module.long$name == "EMT", ]

df.module.long %>%
  ggplot(aes(a.rank, 1)) +  
  geom_tile(aes(fill = value)) +  
  scale_fill_gradientn("Activity", 
                       colours = rev(RColorBrewer::brewer.pal(9, "RdBu")),  
                       limits = c(-scale.limits, scale.limits)) +
  geom_vline(aes(xintercept = which.rank), color = "grey", alpha = 0.8) + 
  facet_wrap(~name, ncol = 1) + 
  theme_minimal() +   
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) + 
  xlab("Functional Activity Spectrum")
 

 # scale_fill_brewer(palette="RdBu") +  
    # scale_fill_viridis_c("Activity", limits = c(-scale.limits, scale.limits)) + 
  # scale_colour_gradientn(colors = colorRampPalette(RColorBrewer::brewer.pal(9, "RdBu"))(100))

  # scale_fill_gradient(colorRampPalette(RColorBrewer::brewer.pal(9, "RdBu"))(100))
# + stat_bin2d(aes(fill = (value)), binwidth = c(3,1))
  # scale_fill_gradient("RdBu")
    # geom_tile(aes(fill = value)) + 
```


```{r save results}

# Run time
end.time <- proc.time()
elapsed.time <- round((end.time - start.time)[[3]], 2)
df.log <- addLogEntry("Run Time (s)", elapsed.time, df.log, "elapsed.time")

df.log_Module_25 <- df.log

```

```{r ph10,  echo = FALSE, eval = TRUE}

try({
out1 <- flex.multiTabLogs(module.logs)
}, silent = T)
```

`r paste(knitr::knit(text = paste(out1, collapse = '\n')))`

Log (Module 25)
===================================== 

```{r table.log_current}
knitr::kable(df.log_Module_25)
```