---
title: "scPipeline Checklist"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
---

```{r, echo = FALSE}

rm(list = setdiff(ls(), c("data.path", "user")))

checklist <- data.frame(
  Rprofile = "",
  data.path = "",
  user = "",
  moduleLog = "",
  Raw_Datasets = "",
  Preprocess_Datasets = "",
  Reference_Datasets = "",
  Gene_Sets = "",
  HTML_Reports = "",
  Module_Outputs = ""
)

```

```{r perform file and folder checks, echo = FALSE, message = FALSE, warning = FALSE}

message("Checking .Rprofile...\n")

file1 <- file.exists(".Rprofile")
if (!file1) {
  message(paste0("\t'.Rprofile' not found 'scPipeline' directory.\n"))
} else {
  message("\t'.Rprofile' found.\n")
  checklist$Rprofile = "X"
}

if (!exists("data.path")) {
  message("\t'data.path' does not exist. Must be defined in .Rprofile. See github.com/NMikolajewicz/scPipeline for help.\n")
} else {
  message("\t'data.path' found\n")
  checklist$data.path = "X"
}

if (!exists("user")) {
  message("\t'user' does not exist. Must be defined in .Rprofile. See github.com/NMikolajewicz/scPipeline for help.\n")
} else {
  message("\t'user' found\n")
  checklist$user = "X"
}

message("Checking data paths\n")
dir1 <- dir.exists(paste0(data.path, "Preprocessed_Datasets/"))
if (!dir1) {
  message(paste0("\t'Preprocessed_Datasets/' not found in '", data.path, "'.\n"))
} else {
  message("\t'Preprocessed_Datasets/' found.\n")
  checklist$Preprocess_Datasets = "X"
}

dir2 <- dir.exists(paste0(data.path, "Raw_Datasets/"))
if (!dir2) {
  message(paste0("\t'Raw_Datasets/' not found in '", data.path, "'.\n"))
} else {
  message("\t'Raw_Datasets/' found.\n")
  checklist$Raw_Datasets = "X"
}

dir3 <- dir.exists(paste0(data.path, "HTML_Reports/"))
if (!dir3) {
  message(paste0("\t'HTML_Reports/' not found in '", data.path, "'.\n"))
} else {
  message("\t'HTML_Reports/' found.\n")
  checklist$HTML_Reports = "X"
}

dir4 <- dir.exists(paste0(data.path, "Reference_Datasets/"))
if (!dir4) {
  message(paste0("\t'Reference_Datasets/' not found in '", data.path, "'.\n"))
} else {
  message("\t'Reference_Datasets/' found.\n")
  checklist$Reference_Datasets = "X"
}

dir5 <- dir.exists(paste0(data.path, "Gene_Sets/"))
if (!dir5) {
  message(paste0("\t'Gene_Sets/' not found in '", data.path, "'.\n"))
} else {
  message("\t'Gene_Sets/' found.\n")
  checklist$Gene_Sets = "X"
}

dir6 <- dir.exists(paste0(data.path, "Module_Outputs/"))
if (!dir6) {
  message(paste0("\t'Module_Outputs/' not found in '", data.path, "'.\n"))
} else {
  message("\t'Module_Outputs/' found.\n")
  checklist$Module_Outputs = "X"
}

file2 <- file.exists(paste0(data.path, "moduleLog.csv"))
if (!file2) {
  message(paste0("\t'moduleLog.csv' not found in '", data.path, "'.\n"))
} else {
  message("\t'moduleLog.csv' found.\n")
  checklist$moduleLog = "X"
}

```
```{r check if packages are installed, echo = FALSE, message = FALSE, warning = FALSE}

message("Checking packages...")

pack.in <- installed.packages()
pack.in <- pack.in[ ,colnames(pack.in) %in% "Package"]

# check scMiko #########################
pack.1 <- c("scMiko")
pack.1.missing <- pack.1[!(pack.1 %in% pack.in)]

if (length(pack.1.missing) > 0) {
  devtools::install_github(
    repo = "NMikolajewicz/scMiko",
    ref = "master",
    auth_token = "a3c1c9b15c496991c952d1fe3ccc52db770f22fa")
}

# check cran packages #########################
pack.2 <- c("dplyr", "ggplot2", "flexdashboard")
pack.2.missing <- pack.2[!(pack.2 %in% pack.in)]

if (length(pack.2.missing) > 0) {
  install.packages(pack.2.missing)
}


# check bioconductor packages #########################
pack.3 <- c("Seurat", "sctransform")
pack.3.missing <- pack.3[!(pack.3 %in% pack.in)]

if (length(pack.3.missing) > 0) {
  BiocManager::install(pack.3.missing)
}

message("Package check complete!")

```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

checklist.output <- t(as.data.frame((checklist)))
checklist.output <- data.frame(Item = rownames(checklist.output), Pass = checklist.output[,1])
rownames(checklist.output) <- NULL

knitr::kable((checklist.output))
```

